### ISSUE TITLE
Don't work with  SH3D on macOS

### ISSUE THREAD

**Issue by idominiki** [shmuelzon/home-assistant-floor-plan#1]
Actually don't work with SH3D on macOS.

SH3D won't start.

**Comment by shmuelzon** [comment]
Figures... Unfortunately, I don't have a way to test this myself.
Can you start SH3D from terminal and post the log?

**Comment by idominiki** [comment]
Info: I use the Mac AppStore Version of Sweet Home 3D

**Comment by shmuelzon** [comment]
Looks like it needs to be compiled with an older version of Java...
I'll see how I can do that properly but, in the meantime, can you try the attached build?
[HomeAssistantFloorPlanPlugin-v0.1.zip](https://github.com/shmuelzon/home-assistant-floor-plan/files/14161797/HomeAssistantFloorPlanPlugin-v0.1.zip)

**Comment by idominiki** [comment]
This build works well! Thanks for your fast support!
