### ISSUE TITLE
No style is defined for element

### ISSUE THREAD

**Issue by edwardtich1** [shmuelzon/home-assistant-floor-plan#102]
When config template card is used as an element in a picture-elements card, I get an error saying "No style is defined for element

``` yaml
type: custom:config-template-card
variables:
  LIGHT_STATE: states['light.badroom_gateway_58b3fcaa0369_rgb_led_58b3fcaa0369'].state
  COLOR_MODE: >-
    states['light.badroom_gateway_58b3fcaa0369_rgb_led_58b3fcaa0369'].attributes.color_mode
  LIGHT_COLOR: >-
    states['light.badroom_gateway_58b3fcaa0369_rgb_led_58b3fcaa0369'].attributes.hs_color
  BRIGHTNESS: >-
    states['light.badroom_gateway_58b3fcaa0369_rgb_led_58b3fcaa0369'].attributes.brightness
entities:
  - light.badroom_gateway_58b3fcaa0369_rgb_led_58b3fcaa0369
element:
  type: image
  image: /local/floorplan/transparent.png?version=56ABE4CBC175363DA0810882244B34FF
  state_image:
    "on": >-
      ${COLOR_MODE === 'color_temp' || (COLOR_MODE === 'rgb' && LIGHT_COLOR &&
      LIGHT_COLOR[0] == 0 && LIGHT_COLOR[1] == 0) ?
      '/local/floorplan/light.badroom_gateway_58b3fcaa0369_rgb_led_58b3fcaa0369.png?version=9E55DA10C259F55AE678EC9E5E57AD84'
      :
      '/local/floorplan/light.badroom_gateway_58b3fcaa0369_rgb_led_58b3fcaa0369.red.png?version=A23183A6996BC3C33E68350F20EC9998'
      }
  entity: light.badroom_gateway_58b3fcaa0369_rgb_led_58b3fcaa0369
style:
  filter: "${ \"hue-rotate(\" + (LIGHT_COLOR ? LIGHT_COLOR[0] : 0) + \"deg)\"}"
  opacity: "${LIGHT_STATE === 'on' ? (BRIGHTNESS / 255) : '100'}"
  mix-blend-mode: lighten
  pointer-events: none
  left: 50%
  top: 50%
  width: 100%

**Comment by shmuelzon** [comment]
Not a lot to go on here... The only reference I'm seeing for this error message is https://github.com/iantrich/config-template-card/issues/52 and that's from 4 years ago. Are you using an up-to-date version of `config-template-card`? Also, have you verified that the entity name is correct? Are there any errors that show up in the browser's developer tools / console?

**Comment by edwardtich1** [comment]
![2024-12-29_08-33-14](https://github.com/user-attachments/assets/f26ff6c5-5ba2-4657-91f5-ed1581c8b6da)
![2024-12-29_08-35-09](https://github.com/user-attachments/assets/30425841-979b-4bc1-b434-e967ca8579ed)

**Comment by shmuelzon** [comment]
The only difference I see between your light and mine is that mine is an `rgb` color mode while yours is `hs`.
I tried to create a fictive light via the MQTT integration by adding the following to my configuration:
```yaml
mqtt:
  light:
    - name: mqtt_json_hs_light
      schema: json
      command_topic: "home/light/set"
      supported_color_modes: ["hs"]
```
Then set the light values to something similar to your (cyan and 49% brightness):
![image](https://github.com/user-attachments/assets/bf486a6b-e14b-4b43-9461-73101e933164)
![image](https://github.com/user-attachments/assets/6cc7e613-54dc-497a-9c76-89cfde8bfff5)

But it still displays as expected...

I'll need your help to debug this. Could you please try to change the `element -> type -> state_image -> on` value to a plain string like: `/local/floorplan/light.badroom_gateway_58b3fcaa0369_rgb_led_58b3fcaa0369.png?version=9E55DA10C259F55AE678EC9E5E57AD84` and see if that changes anything? If not, I'd try removing the `filter` and `opacity` entries from the `style` and lastly, should nothing help, removing the variables one by one. Once we figure out which line is causing the issues, we can try to understand why

**Comment by edwardtich1** [comment]
```yaml
type: custom:config-template-card
variables:
  LIGHT_STATE: states['light.korridor_gateway_58b3fcabb6b6_rgb_led_58b3fcabb6b6'].state
  COLOR_MODE: >-
    states['light.korridor_gateway_58b3fcabb6b6_rgb_led_58b3fcabb6b6'].attributes.color_mode
  LIGHT_COLOR: >-
    states['light.korridor_gateway_58b3fcabb6b6_rgb_led_58b3fcabb6b6'].attributes.hs_color
  BRIGHTNESS: >-
    states['light.korridor_gateway_58b3fcabb6b6_rgb_led_58b3fcabb6b6'].attributes.brightness
entities:
  - light.korridor_gateway_58b3fcabb6b6_rgb_led_58b3fcabb6b6
element:
  type: image
  image: /local/floorplan/transparent.png
  state_image:
    "on": /local/floorplan/light.korridor_gateway_58b3fcabb6b6_rgb_led_58b3fcabb6b6.png
  entity: light.korridor_gateway_58b3fcabb6b6_rgb_led_58b3fcabb6b6

![Uploading 2024-12-29_16-06-28.png…]()

**Comment by shmuelzon** [comment]
What about removing the variables? Those are the only things left that are "special".

**Comment by edwardtich1** [comment]
![2024-12-29_16-14-36](https://github.com/user-attachments/assets/95a2da4f-ca75-4c32-8708-6d0fb147d6e2)

**Comment by shmuelzon** [comment]
I can't seem to find where that error is coming from. It used to exist in `config-template-card`. At least it did on version `1.3.1`:
```bash
wget https://github.com/iantrich/config-template-card/releases/download/1.3.1/config-
grep -i "no style" config-template-card.js
    // If there are no styles, skip unnecessary work
        // When no style is left in the template, parts will be broken as a
        // There can be no style in the template in 2 cases (1) when Shady DOM
            throw new Error('No style defined for element');
```
But it doesn't in newer versions:
```bash
wget https://github.com/iantrich/config-template-card/releases/download/1.3.6/config-template-card.js
grep -i "no style" config-template-card.js
```

Please make sure your version is really updated to v1.3.6 and maybe clear your browser's cache.

**Comment by edwardtich1** [comment]
I have an rgb lamp
but also a style mistake
![2024-12-29_16-54-44](https://github.com/user-attachments/assets/e720d93c-a94b-4160-a625-2ae680b8bb88)

**Comment by shmuelzon** [comment]
Did you verify that you're really using an up-to-date version of `config-template-card`. As shown above, that error doesn't exist in the v1.3.6 version. Please verify the version and clear the browser's cache. Then try again

**Comment by edwardtich1** [comment]
I installed from HACS new version
I looked at the file size and it is twice as large

I manually overwrote the file and everything works!

thank you very much for your help

**Comment by shmuelzon** [comment]
Glad to hear it worked out
