### ISSUE TITLE
No lights found

### ISSUE THREAD

**Issue by idominiki** [shmuelzon/home-assistant-floor-plan#2]
Hi!

I configured all lights as mentioned, but the plugin doesn't list the lights.
![Bildschirmfoto 2024-02-05 um 09 17 51](https://github.com/shmuelzon/home-assistant-floor-plan/assets/62521486/f5ce9b3d-9ebc-412e-99bd-b9efe7cf1beb)

![Bildschirmfoto 2024-02-05 um 09 17 57](https://github.com/shmuelzon/home-assistant-floor-plan/assets/62521486/a9ab1afd-3424-4f1f-b1cc-6cb0e9b23792)

What can I do?

Thanks again!
Dominik

**Comment by shmuelzon** [comment]
Please make sure the lights are visible and have a power > 0%.
Also, have you grouped them? I've never tried that so I'm not sure what that'll do but at least those that aren't grouped should appear

**Comment by idominiki** [comment]
Sorry for that, I have power set to zero.
