### ISSUE TITLE
Daytime renderings

### ISSUE THREAD

**Issue by Zerogiven** [shmuelzon/home-assistant-floor-plan#23]
ok, this is a really "just nice to have" feature cause i know i can solve this otherwise by creating renderings with different daytimes and make a conditional card. but maybe it's "easy" to include this feature :)

cheers
Chris

**Comment by shmuelzon** [comment]
Hey,

Yes, this one is also on my list `Create multiple renders for multiple hours of the day and display in Home Assistant according to local time`. I would probably need to implement `Allow selecting date/time of render` first and then allow a list of dates/times. I don't foresee any issues with implementing this, just need to find the time.

**Comment by Zerogiven** [comment]
too bad that it's about 15 years ago that i wrote some java code... but i know your time thing, it's like me :D

however, i solved it by creating three(morning,day,night) outputs with your plugin and use a conditional card in top of it :)
