### ISSUE TITLE
Change color overlay based on the real light color

### ISSUE THREAD

**Issue by MaJerle** [shmuelzon/home-assistant-floor-plan#32]
**Describe the solution you'd like**
I'm pretty happy with this extension, but I'd like to ask if there is a simple way to generate colored overlays based on the actual color of the light. That applies to RGB lamps.

I didn't find a good way so far. Can CSS mixing feature help here?

**Comment by shmuelzon** [comment]
Hey, this looks like a duplicate of #22 which, to be honest, I still haven't wrapped my head around to see how this can be implemented/automated.
