### ISSUE TITLE
Light entities are not detected anymore if closed earlier

### ISSUE THREAD

**Issue by fabianoarruda** [shmuelzon/home-assistant-floor-plan#33]
**Describe the bug**
I've been using the plugin with great success so far. But sometimes after I start rendering I remember something I need to change so I need to cancel the render and start again. I have 11 light entities and it already takes considerable time. The only way to cancel is by closing the Plugin Window. But when I do that, I notice that the next time I try to render, only the lights that finished rendering on the previous attempt are detected. All other lights are not detected anymore, Even if I restart SH3d. I tried editing them again, like changing name, visibility, percentage, etc, to no avail. The only solution is to delete all the light sources and recreate them again from scratch, so they can be detected again 😕

**To Reproduce**
1. Go to 'Tools', 'Home Assistant Floor Plan'
2. Click on 'Start'
3. click on red dot (Mac OS) to close the plugin window.
4. Next time you open the plugin window, lights that didn't finish render on previous attempt are not detected anymore.

![plugin window](https://github.com/shmuelzon/home-assistant-floor-plan/assets/5299669/940d381f-61fd-46ad-b2e2-a7a83081fd5e)

**Expected behavior**
All 11 light entities should be detected

**Additional context**
I'm running SH3D v7.4 on Mac OS 14.4.1 (intel Mac)

On a side note, I think it would be useful to have a "Cancel" button if, for any reason, you need to start again. For example, you just realized you forgot to set the correct camera angle.

**Comment by fabianoarruda** [comment]
Ah, After looking at [this issue](https://github.com/shmuelzon/home-assistant-floor-plan/issues/2) I realized what's wrong. Some of the lights had power at 0%, I guess this is done automatically during the rendering process, right?

So, in this case, I think the idea of a "Cancel" button would prevent the issue. If clicked before all renderings are finished, you can set all lights back to normal. This routine could be called when closing the window, too. Or perhaps you should prevent the windows from being closed while rendering is active, and the user would need to click "Cancel" first. what do you think?

**Comment by shmuelzon** [comment]
Hey, the problem is that I haven't implemented stopping the rendering thread yet. It's one of the things in my todo list in the README file. Even when you close the window with the X button, the image is still being rendered in the background. That's also why it didn't restore all the light's power values to their original values.
