### ISSUE TITLE
Layout: Small issue on the dialog window

### ISSUE THREAD

**Issue by byDMA** [shmuelzon/home-assistant-floor-plan#34]
Hi, a small layout issue, this field for high spinner is to big. I#m using FlatLaf dark mode, it looks very well
https://www.sweethome3d.com/support/forum/viewthread_thread,12872_lastpage,yes#62795

![GridBagConstrains-LayoutIssue](https://github.com/shmuelzon/home-assistant-floor-plan/assets/91068437/2b31ee6c-1c7a-44d8-b56b-00229e6465f4)

probably Panel.java:

lines 324-326
`add(heightSpinner, new GridBagConstraints(
            3, 2, 1, 1, 0, 0, GridBagConstraints.LINE_START,
            GridBagConstraints.HORIZONTAL, new Insets(0, 0, 0, 0), 0, `0));`

should be
`add(heightSpinner, new GridBagConstraints(
            3, 2, 1, 1, 0, 0, GridBagConstraints.LINE_START,
            GridBagConstraints.HORIZONTAL, componentInsets, 0, 0));`

**Comment by shmuelzon** [comment]
Thanks for that!
First time developing in Java in ~20 years, let alone GUI. That was probably a result of copy-pasting from various examples...
