### ISSUE TITLE
feat: allow select high/low options

### ISSUE THREAD

**Issue by guimatheus92** [shmuelzon/home-assistant-floor-plan#37]
Hello!

I will be honest with you. This project looks amazing and very well robust!
It was not very easy to find a solution like this tho, I have also built something similar, it was working in version `1x` all generating all possible combinations but I had the same problem as you: Rooms with multiple light sources, which led to many images generated and impossible to do.

This is my repo: `https://github.com/guimatheus92/SweetHome3D_HomeAssistant_Lightning/tree/v1.1.0`

In there you will notice that there is a `high ` and `low` options where user can set what he actually needs. Do you mind improving your `README` file with how your project is structured? I am not a Java expert, but I can start contributing to this amazing solution, and I will abandon my project because your's is way ahead of me 🥇

**Comment by shmuelzon** [comment]
Hey,

What do you mean by high/low? The quality level of the render?
If so, that's on my TODO list in the README file:
>  Allow selecting renderer (SunFlow/Yafaray) and level (high/low)

It shouldn't be too difficult to add. Right now it's just hard-coded at https://github.com/shmuelzon/home-assistant-floor-plan/blob/752fb389817aabc159886dce8b22b3893cc4dcd5/src/com/shmuelzon/HomeAssistantFloorPlan/Controller.java#L369

I'm by no means a Java expert and this is the first thing I've written in Java in the last 20 years.
I hope to get around to some of the simpler things in my TODO once I finish a different project I'm working on.

Thanks for your support!
