### ISSUE TITLE
Q/A: Is a light within a group is being considered?

### ISSUE THREAD

**Issue by guimatheus92** [shmuelzon/home-assistant-floor-plan#39]
I have a project that has LED's and other lights object in Sweet Home that I am grouping them together to facilitate the work in there.

For example:

![image](https://github.com/shmuelzon/home-assistant-floor-plan/assets/11640754/fd6b49be-8614-4dea-affe-c935c078297c)

Is this scenario going to be considered fine?

**Comment by shmuelzon** [comment]
Hey,

A recent fix (#31) also looks for lights inside groups but, IIRC, doesn't necessarily turn them on together. For that to happen, all relevant lights still need to have the same name, regardless if they're in a group or not.
