### ISSUE TITLE
feat: Avoid exposing "Home" from SH3D to UI; Use function for empty project

### ISSUE THREAD

**Issue by guimatheus92** [shmuelzon/home-assistant-floor-plan#41]
I'd rather not expose `Home` directly to the UI. If you really want to indicate the project is empty, create a function specifically for that

_Originally posted by @shmuelzon in https://github.com/shmuelzon/home-assistant-floor-plan/pull/40#discussion_r1667321494_

**Comment by guimatheus92** [comment]
@shmuelzon How would you suggest doing this please? To be honest I didn't understand much and I am no expert in Java. So I would like to get some inputs from you please, so I can try to make this work in a proper way then. Thanks!

**Comment by shmuelzon** [comment]
We could create a function in the controller called `isProjectEmpty()` or something like that and it would contain the same logic you had in the panel to check if there's any furniture in the project.

**Comment by guimatheus92** [comment]
Thanks @shmuelzon! Will follow your input. Do you want me to send one PR at a time? I don't know if I should wait your approval or send all of them, based on your last comment.

**Comment by shmuelzon** [comment]
Thank you for putting the effort!
I prefer one pull request for each new feature/task. It'll make things simpler in the git history and release notes for the new version

**Comment by guimatheus92** [comment]
Ok, thanks! Can you review my opened PR and approve it please? I followed your previous suggestions. So that I can open another one.
