### ISSUE TITLE
[Q&A]: How does a release happen?

### ISSUE THREAD

**Issue by guimatheus92** [shmuelzon/home-assistant-floor-plan#52]
**Question**
Hi @shmuelzon!

After our changes last week, I saw that CI action succeed but no new release has been created with the latest changes.

How do you do generally? I know I can generate one locally, but having one here updated is also important.

**Comment by shmuelzon** [comment]
Hey, releases are generated when I add a tag to the repository. I wanted to wait until your PR will be merged before I create a new release but will only have time to code-review it over the weekend.

**Comment by guimatheus92** [comment]
Oh, I see. I thought you wanted to create one release per each PR or something similar. Otherwise, the release/tag can have a delay depending on this change. That's okay then.

Let me know your comments on #49, and I will try to push this week as well.

**Comment by guimatheus92** [comment]
> BTW - Just released v0.5.0. Thanks for all you help in improving this plugin!

I loved your project since beginning, it deserves attention! Thanks for letting me contribute to it 🚀
