### ISSUE TITLE
Please update repository with more detailed instructions for less-advanced users

### ISSUE THREAD

**Issue by ha-elguano** [shmuelzon/home-assistant-floor-plan#53]
I think you need some extended instructions, beyond what is needed to run the plugin-render, such as:
Where to load the pictures: local is www, and you should create a folder called floorplan and drop all the files there (from the render or the floorplan directory that is created)?

- It's critical to better explain what do you do with the yaml file, or rather the entire floorplan output from the plugin, after it's done rendering. It should tell users to create a picture-element card in Home Assistant, to go to "Edit YAML" mode, and to cut and paste the plugin-generated floorplan.yaml contents into the picture elements yaml. Also, tell users where to put the render files (which directory) and if they need separate tools in HA (like File Editor) to do so. Right now, the plugin works, but just outputs images and yamls and it's very difficult for less advanced users to know what to do next.

- Explain how to select the desired perspective for rendering. You have to set the SH3D 3d view to exactly how you want it, before activating the plugin.

- Explain to users how to change the rendering settings for the plugin? You have to go to “Create photo…” in SH3D and change settings there. You don’t actually have to render anything or save anything, just make the changes there, and close the dialogue.

- Explain better why “remove ceiling lights” should be selected? It doesn’t actually remove YOUR ceiling lights, just a global ceiling light for people who haven’t added lights to their floorplans.

- Remind user to NOT MOVE the 3D view or make changes in SH3D while it’s rendering in the background! These will get captured by the plugin as it scripts the renders one by one. Hit the Start button and walk away.

**Comment by guimatheus92** [comment]
This is well explained among the README file, specially in the [FAQ](https://github.com/shmuelzon/home-assistant-floor-plan?tab=readme-ov-file#frequently-asked-questions) section. What topic do you think is missing or you didn't understand clearly after reading all documentation?

**Comment by ha-elguano** [comment]
Ah, I don't think the FAQ section was there when I last checked (a few weeks ago). I think it may have been updated per some feedback I left in the Home Assistant forums?  TY! This addresses most of my issues, please feel free to close!

**Comment by guimatheus92** [comment]
Yeah, we have improved since then and I also took your opinion in HA Community thread regarding this plugin in consideration 😄

**Comment by shmuelzon** [comment]
Thanks @ha-elguano for the suggestions and @guimatheus92 for updating the documentation!
I'm closing this issue for now and we can open a new one if anything else is needed.
