### ISSUE TITLE
Remember last-used confic/settings for plugin

### ISSUE THREAD

**Issue by ha-elguano** [shmuelzon/home-assistant-floor-plan#54]
Is there a way for the plugin to remember the last settings used (which directory to output renders to, resolution, etc.)? I have to manually change these every time.

**Comment by shmuelzon** [comment]
I don't know :)
I wanted to support something like this (and more), and posted a question in the [SH3D forum](https://www.sweethome3d.com/support/forum/viewthread_thread,13261) a couple of hours ago.

We'll see...

**Comment by shmuelzon** [comment]
Hey, I got an answer and have something working. The changes done in the plugin's window can now be saved as a part of the project file but only if the project file is saved.
This raises the question of whether changes done in the plugin window (resolution, renderer, output directory, etc.) should mark the project as modified (shows an asterisk in the title bar and a popup telling you that changes were made when trying to exit SH3D) or not.

On one hand, if the project isn't marked as modified, the user can exit SH3D without saving and their settings will be back to default the next time. On the other hand, if we do mark the project as modified, it might seem odd to the user that something was changed (as they probably didn't expect to change anything in the home) and decide to exit without saving to make sure no unintentional changes were kept.

What do you think?

**Comment by ha-elguano** [comment]
Hey, thanks so much for following up on that.

As a user, if I am playing with new renders, I'm most likely making changes all over, so I would expect to see a "project is modified" dialogue frequently. Personally, I would prefer the first behavior (make changes to the plugin, see a modification to remind to save, next time I load I know I will have the same resolution/file directory presets. Ty!
