### ISSUE TITLE
Persistent lights

### ISSUE THREAD

**Issue by ha-elguano** [shmuelzon/home-assistant-floor-plan#55]
Can we get a special flag/name we can assign to lights that we want on all the time (not rendered as "off" in the base.png file? 

I have a light that I always want to render as lit, regardless of the floorplan lights I want to switch on/off.

**Comment by shmuelzon** [comment]
Just to better understand the use-case, this is something that's not controlled by HA and that's why you want it in the base image?

**Comment by ha-elguano** [comment]
Simply because some lights can be part of the home, even if not automated, just like a bed or a bookcase, and I'd like them rendered if possible for accuracy. For instance, I have a nightlight that is on all the time, and a small light illuminating a spot outside that is solar-powered. They don't need to be controlled, but I'd like the render to show them as they are.  Right now, because all lights are turned off for the base.png render, there's no way I can tell the plugin "please ignore this light and render it in its current state in all cases."  Ty for considering!

**Comment by guimatheus92** [comment]
> Simply because some lights can be part of the home, even if not automated, just like a bed or a bookcase, and I'd like them rendered if possible for accuracy. For instance, I have a nightlight that is on all the time, and a small light illuminating a spot outside that is solar-powered. They don't need to be controlled, but I'd like the render to show them as they are. Right now, because all lights are turned off for the base.png render, there's no way I can tell the plugin "please ignore this light and render it in its current state in all cases." Ty for considering!

Do you mind sharing an example of how would look like? Maybe this can come along with preferrend settings for the user as well.

**Comment by ha-elguano** [comment]
Sure, here's a basic example.

1. [This is the base.png image](https://imgur.com/fwfdfLL.jpg) of a hallway in my home. It shows no lights on, since it's the base file.  Any and all lights I have in SH3D are turned off for the render.
2. However, the hallway normally has two night lights that are always on, regardless of whether my hallway's automated ceiling lights are active. [This is what I want it to look like in the base.png](https://imgur.com/EOG3IVj.jpg) because these lights are always on at night. I've upped the brightness and color a bit to accentuate.
3. When the automated hallway lights are on, [it should look like this](https://imgur.com/JDm9l7i.jpg) (the night lights are still on, but the plugin creates are render with the main white-light hallway lights are turned on).

 Right now, the only way I can hope to kludge the effect is to start the plugin, and then try to add the lights before the rendering begins.

My suggestion, if easy to do, is to allow the user to give such lights a name that is recognized and exempted from script control when the plugin runs, e.g., "light.alwayson".

**Comment by guimatheus92** [comment]
Thank you very much for sharing this example.

@shmuelzon from my point of view, this could also be another property set in the user project configuration that we are talking on #44. For example, user set that light as an entity name (`light.hallway_bulb`) and we can create a property called `always_on: true` for this entity in the settings:

entities:
  light.hallway_bul:
      state_icon: true
      state_badge: false
      always_on: true

**Comment by shmuelzon** [comment]
Yes, agreed. We should simply not include it in the list of light combinations generated by `getCombinations()` and so we won't set it's power nor create a render specifically for it. For completeness, we should also consider this somehow when calculating the number of renders we're going to generate
