### ISSUE TITLE
Show all entities and not only lights in panel

### ISSUE THREAD

**Issue by guimatheus92** [shmuelzon/home-assistant-floor-plan#63]
**Is your feature request related to a problem? Please describe.**
When **Define settings per entity and save persistently** feature is added into this project, one thing that is missing is entities supported by this project that is not a light to be shown in the panel.

My example was: I would like to change the Tap Action option from `toggle` to `show-more` for one entity that is not a light, but that entity is not there in the list.

**Describe the solution you'd like**
I don't know if we should add all entities in one panel with scroll (user can have more than 100 entity - I have 60), or add one tab for lights and **others entities**.

**Describe alternatives you've considered**
N/A

**Comment by shmuelzon** [comment]
Hey, the lights are grouped according to the rendering mode and I wouldn't want to overload that tree by adding the other entities to it. What's more, while they, technically, belong to some room, we don't regard them as such and they're just overlayed on top. I would suggest placing them in a separate scrollable list, maybe beside the lights tree.

**Comment by guimatheus92** [comment]
Yes, that's what I meant by adding another tab or something to display other entities on my feature request.

But to be honest, I would need help on this one. Since there a couple of entities that I would like to change some settings and they are not lights.
