### ISSUE TITLE
Difference between features

### ISSUE THREAD

**Issue by guimatheus92** [shmuelzon/home-assistant-floor-plan#68]
**Question**
Is there any difference between the features below from TODO list we have in README file?

- [X] Allow enabling/disabling/configuring state-icon
- [ ] Allow defining, per entity, if it should be an icon or label, and save
      that persistently

**Additional context**
I would like to keep improving this project, so more clear idea of that those features mean would help very much.

**Comment by shmuelzon** [comment]
Who knows what I was thinking... I saw that too earlier but figured I'd fix it along with another commit.

The second one (along with the "configuring" part of the first) was done in #62  and the enabling/disabling (which is basically allowing to hide the icon) was done in #65. They're both completed now.

**Comment by guimatheus92** [comment]
Hahahahaha sounds fair, thanks then!
