### ISSUE TITLE
Change ov floorplan images in Hassio

### ISSUE THREAD

**Issue by FilipCZE** [shmuelzon/home-assistant-floor-plan#76]
**Question**
Hi!

I successfully loadwd the picture card, yaml, *.png floorplans to www (/local) 

Then I made some changes at floorplan in Sweethome and wanted to change the *.png files at Hassio.

the issue is, even when I deleted all the floorplan images they still are present on dashboard. ( the old ones) - yes I rebooted firstly hassio then whole Pi. 

Where can be these files stored as duplicates? 

When I put new render of floorplans to the /www folder, there was stil the old picture at the dashboard 🥴

thnaks for advice :)

**Comment by shmuelzon** [comment]
Hey, did you also copy/paste the new YAML file into Home Assistant? That should include a mechanism that will force the browser to use the updated images instead of the old ones it cached

**Comment by FilipCZE** [comment]
I did copy only first part from the bedinning including the new png files. The entities I have left the same...

But Its OK now. Might be the cache of the browser or whatever... 

So closing the issue

thanks!!
