### ISSUE TITLE
Files not accessible from internet.

### ISSUE THREAD

**Issue by adlertag1** [shmuelzon/home-assistant-floor-plan#90]
Everything works fine, until the HA is accessed from the internet. The images can not be opened. If the ?version extension is deleted from the base.png, then it opens. However the entities are not working. I discovered that the . between the entity type and the name causes the proble. So if I rename light.something.png to light_something.png then it works from local and from internet access too.

**Comment by shmuelzon** [comment]
Hey, this works fine for me both locally and via a reverse proxy. How are you accessing your instance from the Internet? Is there anything between your device and the HA instance? Are you using a browser or a mobile app?

**Comment by adlertag1** [comment]
> Hey, this works fine for me both locally and via a reverse proxy. How are you accessing your instance from the Internet? Is there anything between your device and the HA instance? Are you using a browser or a mobile app?

Hi! Thanks for your answer. I'm accessing my instance from the internet via direct ip, cloudflared DNS, I'm trying it with both mobile app and windows browser. When I'm working with vpn its's awesome. But from outside the HA doesn't want to open the images,

**Comment by adlertag1** [comment]
When I replace the link with another file inside the www folder it displays it correctly.

**Comment by shmuelzon** [comment]
Does it also work with other files of you add the query string (question mark followed by `key=value `) like the version?
What about if other files have a dot in their name?

To be honest, I have no idea why this would happen. The HA server has no problems with these file names, as you can also see when browsing locally. I access my instance via a reverse proxy and have no issues with the file names. Maybe Cloudflare is doing something weird? I don't use them so I'm not familiar with what they do.

**Comment by adlertag1** [comment]
I will try that what happen to other filse with query string and extra dots. But I figured out a solution. Don't know why it works, but it sure does. I have to restart the HA host. Not only the instant, but the whole VM hosting it. Aftrer the restart it works! So I don't think the bug is in your code. I would like to say a big thank you for this very cool project! It makes creating floor plans very very easy.

**Comment by shmuelzon** [comment]
Glad to hear you got it to work and thanks for the kind words!
