### ISSUE TITLE
Add Button entity

### ISSUE THREAD

**Issue by dantol1** [shmuelzon/home-assistant-floor-plan#94]
I have a button entity that I currently set as a switch in the floor plan and just change the type in the created yaml file, it would be great if it would just recognize it directly.
I guess it should act the same as a switch, just that the tap action is click instead of toggle.

**Comment by shmuelzon** [comment]
Hey, seems simple enough. I left the "toggle" action since it keeps the code cleaner and seemed to work with a quick test I did. I'll create a new release soon
