### ISSUE TITLE
Domains niet included when grouped

### ISSUE THREAD

**Issue by DigiLive** [shmuelzon/home-assistant-floor-plan#97]
**Describe the bug**
I'm not sure to report it as a bug or as a feature-request, but...
Entities of domains, other than `light`, aren't picked up by the plugin if they're in a furniture-group.

**To Reproduce**
1. Place multiple furniture, other than a light-source on the map.
2. Name the furniture to entitiy0names of your HASS. E.g. `binary_sensor.presence`, `climate.livingroom`, etc.
3. Start the plugin.
4. See the entities listed.
![image](https://github.com/user-attachments/assets/a195c22a-f86e-4d48-9b2d-14214c1728a9)

5. Group the furniture together.
6. Start the plugin.
7. See the entities other than `light`, not listed.
![image](https://github.com/user-attachments/assets/5e168258-1068-44b9-8937-837ad0da8523)

**Expected behavior**
All entities of the light domain and the domains listed at https://github.com/shmuelzon/home-assistant-floor-plan?tab=readme-ov-file#preparation listed.

**Additional context**
I would very much be able to group furniture together to keep things organized.
Think of grouping furniture for devices with multiple entities, like a Hue motion sensor.
Or a custom build cabinet which consists of multiple models (compartments, decoration, but also switches and such).

**Comment by shmuelzon** [comment]
Thanks, it's fixed now. I'll create an official release soon
