### ISSUE TITLE
Normal ?

### ISSUE THREAD

**Issue by MrNoooooooob** [shmuelzon/home-assistant-floor-plan#98]
Is it normal that it has to render so many images?

![Bildschirmfoto 2024-12-23 um 19 46 29](https://github.com/user-attachments/assets/5b00da63-f309-4467-983a-4f142c45c6e8)

**Comment by shmuelzon** [comment]
Hey, you've selected the "Complete renders" mode so yes, it'll render a separate image for every light combination. You have 14 light that each one has 2 states (on or off) so that's `2^14=16384` combinations. I suggest you start with the CSS mixing mode and only try the others if you're not pleased with the results.

**Comment by MrNoooooooob** [comment]
Is the quality not worse because of this?

**Comment by shmuelzon** [comment]
The quality of rendering each combination separately will, most likely, be best but is a tradeoff between time/resources and quality. For me, the CSS rendering mode is more than enough and the others aren't worth the time to render them nor the space to save all 16K images.

**Comment by MrNoooooooob** [comment]
If the Sweet Home 3D also supported ray tracing, it didn't take that long.

**Comment by shmuelzon** [comment]
It does support ray tracing, just not GPU accelerated.
Personally, I prefer YafaRay. I suggest you create one render of each from SH3D's menus, not the plugin, and decide which one looks better to you and then, once you're pleased with the results, use the plugin to generate the floor plan for Home Assistant

**Comment by MrNoooooooob** [comment]
According to their website, I couldn't tell that it supports ray tracing. But I wrote to the manufacturer of the program. I work on a Mac. The maximum RAM that the program can use is 6GB.

I tried 20GB but it doesn't support that.

I tried it once without the tool and once with the tool and both had the same result. The quality is just not the best, as you can see in the picture
![Bildschirmfoto 2024-12-24 um 09 08 15](https://github.com/user-attachments/assets/c6629cf4-667a-4e51-a23a-3efe60508a7e)

**Comment by shmuelzon** [comment]
The rendering engines aren't part of SH3D but are separate projects that SH3D makes use of:
* https://github.com/fpsunflower/sunflow
* https://github.com/YafaRay/libYafaRay

The floorplan plugin uses SH3D's image rendering process so the results should be the same if you render directly of via the plugin.
As for the quality, yes, it has also been my experience that the images are grainy/noisy but, for me, that's not a show-stopper.

**Comment by shmuelzon** [comment]
BTW - If you're using a Mac, can you please share your experience on https://github.com/shmuelzon/home-assistant-floor-plan/issues/91? It seems the Mac's application sandbox is causing some issues for some.

**Comment by MrNoooooooob** [comment]
> BTW - If you're using a Mac, can you please share your experience on #91? It seems the Mac's application sandbox is causing some issues for some.


The problem with the folders that you can't change them is due to Sweet Home 3D or the plugin just doesn't allow it and it's actually not disturbing

**Comment by MrNoooooooob** [comment]
> The rendering engines aren't part of SH3D but are separate projects that SH3D makes use of:
> 
> * https://github.com/fpsunflower/sunflow
> * https://github.com/YafaRay/libYafaRay
> 
> The floorplan plugin uses SH3D's image rendering process so the results should be the same if you render directly of via the plugin. As for the quality, yes, it has also been my experience that the images are grainy/noisy but, for me, that's not a show-stopper.
I'll take a closer look later to see why the pictures are so grainy

**Comment by shmuelzon** [comment]
Thanks!
I'm closing this issue for now as the original question was answered.
